# Generated by Django 5.2.14 on 2026-05-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
