# Generated by Django 5.2.14 on 2026-05-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_ubicacion_latitud_ubicacion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoaccesibilidad',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('sala', 'Sala de Clases'), ('zona_tranquila', 'Zona Tranquila'), ('entrada', 'Entrada Principal')], max_length=50),
        ),
    ]
