# Generated by Django 5.2.14 on 2026-05-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_alter_puntoaccesibilidad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoaccesibilidad',
            name='tipo',
            field=models.CharField(choices=[('ascensor', 'Ascensor'), ('rampa', 'Rampa'), ('bano', 'Baño Accesible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('sala', 'Sala de Clases'), ('zona_tranquila', 'Zona Tranquila'), ('entrada', 'Entrada Principal')], max_length=50),
        ),
    ]
