# Generated by Django 5.2.14 on 2026-05-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('sala', 'Sala de Clases'), ('zona_tranquila', 'Zona Tranquila'), ('entrada', 'Entrada Principal'), ('entrada', 'Entrada Segundaria'), ('rampa', 'Rampa de Acceso')], max_length=50),
        ),
    ]
