# Generated by Django 5.2.14 on 2026-05-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('sala', 'Sala de Clases'), ('zona_tranquila', 'Zona Tranquila'), ('entrada_principal', 'Entrada Principal'), ('entrada_secundaria', 'Entrada Secundaria'), ('rampa', 'Rampa de Acceso'), ('banio', 'Baño Accesible')], max_length=50),
        ),
    ]
