# Generated by Django 5.2.14 on 2026-05-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0007_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ubicaciones/'),
        ),
    ]
