# Generated by Django 5.2.14 on 2026-06-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0008_ubicacion_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
                ('tipo_barrera', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
            ],
        ),
    ]
